version: '3'
services:
  nwn-order:
    hostname: nwn-order
    image: golang:1.11.1-stretch
    env_file: ${PWD-.}/config/nwnorder.env
    volumes:
      - ${PWD-.}/order:/go/order
    working_dir: /go/order
    command: bash -c "go mod download && go run *.go"
    ports:
      - "5750:5750/tcp"
  redis:
    image: healthcheck/redis:latest
    command: ["redis-server", "--appendonly", "no"]
    hostname: redis
    volumes:
      - ${PWD-.}/redis:/data
    restart: unless-stopped
  nwnxee-server:
    hostname: nwnxee-server
    image: nwnxee/unified:latest
    env_file: ${PWD-.}/config/nwserver.env
    stdin_open: true
    tty: true
    links:
      - "redis:redis"
      - "nwn-order:nwn-order"
    depends_on:
      - nwn-order
      - redis
    volumes:
      - ${PWD-.}/logs:/nwn/run/logs.0
      - ${PWD-.}/server/:/nwn/home
      - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
    restart: always
    ports:
      - "5121:5121/udp"